config/routes.rb
Rails.application.routes.draw do
  root to: "homes#top"
  devise_for :users, :controllers => {
    :registrations => 'users/registrations'
   }

   # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

   resources :books, only: [:edit, :update, :create, :index, :show, :destroy]
   resources :users, only: [:edit, :index, :show, :update]

   get 'home/about' => 'homes#about', as:'about'

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_one_attached :profile_image
  has_many :books, dependent: :destroy
  
  validates :name, uniqueness: true, length: {minimum: 2, maximum: 20 }
  validates :introduction, length: {maximum: 50 }
  
  
  def get_profile_image(width,height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no-image2.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width,height]).processed
  end
  
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  #protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  def after_sign_up_path_for(resource)
    #super(resource)
    flash[:notice] = "Welcome! You have signed up successfully."
    #user_path(current_user.id)
    user_path(current_user.id)
  end

end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def edit
    @user = User.find(params[:id])
  end

  def index
    @book = Book.new
    @users = User.all
  end

  def show
    @book = Book.new
    @user = User.find(params[:id])
    @books = @user.books
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
  
  def correct_user
    @user = User.find(params[:id])
    unless @user == current_user
    redirect_to user_path(current_user)
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_info.html.erb
<h2>User info</h2>
<%= image_tag current_user.get_profile_image(100,100) %>
<table class="table">
  <tbody>
    <tr>
      <th>name</th>
      <th><%= current_user.name %></th>
    </tr>
    <tr>
      <th>introduction</th>
      <th><%= current_user.introduction %></th>
    </tr>
  </tbody>
</table>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>User info</h2>

      <div class="error_explanation">
        <% if @user.errors.any? %>
        <h3><%= @user.errors.count %>error prohibited this obj from being saved:</h3>
        <ul>
          <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
        <% end %>
      </div>

      <%= form_with model: @user do |f| %>
      <div class="form-group">
        <label for="inputName">Name</label>
        <%= f.text_field :name, id:"inputName", class: "form-control" %>
        </div>
        <div class="form-group">
          <laebl for="inputImage">Image</laebl>
          <%= f.file_field :profile_image, id:"inputImage", accept: "image/*" , class: "form-control-file" %>
        </div>
        <div class="form-group">
          <label for="inputIntroduction">Introduction</label>
          <%= f.text_area :introduction, id:"inputIntroduction", class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.submit "Update User", class: "btn btn-secondary" %>
        </div>
        <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">

      <%= render "info" %>

      <div class="row">
      <%= link_to edit_user_path(current_user.id), class: "btn btn-outline-secondary btn-block" do %>
      <i class="fas fa-user-cog"></i>
      <% end %>

      </div>
      <h2 class="mt-3">New book</h2>
      <%= form_with model: @book do |f| %>
      <div class="form-group">
        <label for="inputTitle">Title</label>
        <%= f.text_field :title, id:"inputTitle", class: "form-control" %>
      </div>
      <div class="form-group">
        <label for="inputBody">Opinion</label>
        <%= f.text_area :body, id:"inputBody", class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.submit "Create Book", class: "btn btn-success" %>
      </div>
      <% end %>

    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <table class="table table-hover">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th></th>
          </tr>
        </thead>

        <tbody>
          <% @users.each do |user| %>
          <tr>
            <td>
              <%= image_tag user.get_profile_image(80,80) %>
            </td>
            <td>
              <%= user.name %>
            </td>
            <td>
              <%= link_to "Show", user_path(user.id) %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>

  </div>
</div>

app/views/users/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
      <%= image_tag @user.get_profile_image(100,100) %>
      <table class="table">
        <tbody>
          <tr>
            <th>name</th>
            <th><%= @user.name %></th>
          </tr>
          <tr>
            <th>introduction</th>
            <th><%= @user.introduction %></th>
          </tr>
        </tbody>
      </table>

      <div class="row">
        <%= link_to edit_user_path(@user.id), class: "btn btn-outline-secondary btn-block" do %>
        <i class="fas fa-user-cog"></i>
        <% end %>
      </div>

      <h2 class="mt-3">New book</h2>
      <%= form_with model: @book do |f| %>
      <div class="form-group">
        <label for="inputTitle">Title</label>
        <%= f.text_field :title, id:"inputTitle", class: "form-control" %>
      </div>
      <div class="form-group">
        <label for="inputBody">Opinion</label>
        <%= f.text_area :body, id:"inputBody", class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.submit "Create Book", class: "btn btn-success" %>
      </div>
      <% end %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
          <tr>
            <td>
              <%= link_to user_path(book.user.id) do %>
                <%= image_tag book.user.get_profile_image(80,80) %>
              <% end %>
            </td>
            <td>
              <%= link_to book_path(book.id) do %>
                <%= book.title %>
              <% end %>
            </td>
            <td>
              <%= book.body %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>