config/routes.rb
Rails.application.routes.draw do
  root to: "homes#top"
  devise_for :users, :controllers => {
    :registrations => 'users/registrations'
   }

   # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

   resources :books, only: [:edit, :update, :create, :index, :show, :destroy]
   resources :users, only: [:edit, :index, :show, :update]

   get 'home/about' => 'homes#about', as:'about'

end

app/models/book.rb
class Book < ApplicationRecord
  
  belongs_to :user
  
  validates :title, presence: true
  validates :body, presence: true, length: {maximum: 200 }

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def create
    @books = Book.all
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book.id)
    else
      render :index
    end
  end

  def index
    @book = Book.new
    @books = Book.all
  end

  def show
    @book = Book.new
    @books = Book.find(params[:id])
  end


  def destroy
    @book = Book.find(params[:id])
    @book.delete
    redirect_to books_path
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
     flash[:notice] = "You have updated book successfully."
     redirect_to book_path(@book.id)
    else
     render :edit
    end
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end
  
  def correct_user
    @book = Book.find(params[:id])
    unless @book.user == current_user
    redirect_to books_path
    end
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>Editing Book</h1>
      
      <div class="error_explanation">
        <% if @book.errors.any? %>
        <h3><%= @book.errors.count %>error prohibited this obj from being saved:</h3>
        <ul>
          <% @book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
        <% end %>
      </div>
      
      <%= form_with model: @book do |f| %>
      <div class="form-group">
        <label for="inputTitle">Title</label>
        <%= f.text_field :title, id:"inputTitle", class: "form-control" %>
      </div>
      <div class="form-group">
        <label for="inputBody">Opinion</label>
        <%= f.text_area :body, id:"inputBody", class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.submit "Update Book", class: "btn btn-success" %>
      </div>
      <% end %>
      <%= link_to "Show", book_path(@book.id) %>
      |
      <%= link_to "Back", books_path %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="error_explanation">
    <% if @book.errors.any? %>
    <h3><%= @book.errors.count %>errors prohibited this obj from being saved:</h3>
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
    <% end %>
  </div>
  <div class="row">
    <div class="col-md-3">

      <%= render "users/info" %>

      <div class="row">
      <%= link_to edit_user_path(current_user.id), class: "btn btn-outline-secondary btn-block" do %>
      <i class="fas fa-user-cog"></i>
      <% end %>

      </div>
      <h2 class="mt-3">New book</h2>
      <%= form_with model: @book do |f| %>
      <div class="form-group">
        <label for="inputTitle">Title</label>
        <%= f.text_field :title, id:"inputTitle", class: "form-control" %>
      </div>
      <div class="form-group">
        <label for="inputBody">Opinion</label>
        <%= f.text_area :body, id:"inputBody", class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.submit "Create Book", class: "btn btn-success" %>
      </div>
      <% end %>

    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
          </tr>
        </thead>

        <tbody>
          <% @books.each do |book| %>
          <tr>
            <td>
              <%= link_to user_path(book.user.id) do %>
                <%= image_tag book.user.get_profile_image(80,80) %>
              <% end %>
            </td>
            <td>
              <%= link_to book_path(book.id) do %>
                <%= book.title %>
              <% end %>
            </td>
            <td><%= book.body %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">

      <h2>User info</h2>
      <%= image_tag @books.user.get_profile_image(100,100) %>
      <table class="table">
        <tbody>
          <tr>
            <th>name</th>
            <th><%= @books.user.name %></th>
          </tr>
          <tr>
            <th>introduction</th>
            <th><%= @books.user.introduction %></th>
          </tr>
        </tbody>
      </table>

      <div class="row">
      <%= link_to edit_user_path(@books.user.id), class: "btn btn-outline-secondary btn-block" do %>
      <i class="fas fa-user-cog"></i>
      <% end %>

      </div>
      <h2 class="mt-3">New book</h2>
      <%= form_with model: @book do |f| %>
      <div class="form-group">
        <label for="inputTitle">Title</label>
        <%= f.text_field :title, id:"inputTitle", class: "form-control" %>
      </div>
      <div class="form-group">
        <label for="inputBody">Opinion</label>
        <%= f.text_area :body, id:"inputBody", class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.submit "Create Book", class: "btn btn-success" %>
      </div>
      <% end %>

    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <table class="table">
        <tbody>
          <td>
            <%= link_to user_path(@books.user.id) do %>
              <%= image_tag @books.user.get_profile_image(100,100) %></br>
              <%= @books.user.name %>
            <% end %>
          </td>
          <td>
            <%= link_to book_path(@books.id) do %>
              <%= @books.title %>
            <% end %>
          </td>
          <td>
            <%= @books.body %>
          </td>
          <% if @books.user == current_user %>
          <td>
            <%= link_to "Edit", edit_book_path(@books.id), class: "btn btn-sm btn-success" %>
          </td>
          <td>
            <%= link_to "Destroy", book_path(@books), method: :delete, "data-confirm" => "本当に消しますか？", class: "btn btn-sm btn-danger" %>
          </td>
          <% end %>

        </tbody>
      </table>

    </div>
  </div>
</div>