config/routes.rb
Rails.application.routes.draw do
  root to: "homes#top"
  devise_for :users, :controllers => {
    :registrations => 'users/registrations'
   }

   # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

   resources :books, only: [:edit, :update, :create, :index, :show, :destroy]
   resources :users, only: [:edit, :index, :show, :update]

   get 'home/about' => 'homes#about', as:'about'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">


    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="/"><span>Bookers</span></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="navbar-collapse collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
              <li>
                <%= link_to user_path(current_user.id) ,class: 'nav-link text-light' do %>
                <i class="fas fa-home"></i> Home
                <% end %>
              </li>
              <li>
                <%= link_to users_path ,class: 'nav-link text-light' do %>
                <i class="fas fa-users"></i> Users
                <% end %>
              </li>
              <li>
                <%= link_to books_path ,class: 'nav-link text-light' do %>
                <i class="fas fa-book-open"></i> Books
                <% end %>
              </li>
              <li>
                <%= link_to destroy_user_session_path, method: :delete ,class: 'nav-link text-light' do %>
                <i class="fas fa-sign-out-alt"></i> Log out
                <% end %>
              </li>
              <% else %>
              <li>
                <%= link_to root_path ,class: 'nav-link text-light' do %>
                <i class="fas fa-home"></i> Home
                <% end %>
              </li>
              <li>
                <%= link_to about_path ,class: 'nav-link text-light' do %>
                <i class="fas fa-link"></i> About
                <% end %>
              </li>
              <li>
                <%= link_to new_user_registration_path ,class: 'nav-link text-light' do %>
                <i class="fas fa-user-plus"></i> Sign up
                <% end %>
              </li>
              <li>
                <%= link_to new_user_session_path ,class: 'nav-link text-light' do %>
                <i class="fas fa-sign-in-alt"></i> Log in
                <% end %>
              </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>

    <main>
    <p><%= flash[:notice] %></p>

    <%= yield %>
    </main>

    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>